apiVersion: v1
kind: Service
metadata:
  name: stoqr-postgres
  labels:
    app: stoqr-postgres
spec:
  ports:
    - port: 5432
      protocol: TCP
      name: http
  selector:
    app: stoqr-postgres
