apiVersion: v1
kind: Service
metadata:
  name: stoqr
  labels:
    app: stoqr
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: api
    - port: 8081
      protocol: TCP
      name: ui
  selector:
    app: stoqr
